apiVersion: v1
data:
  images.json: |-
    [
      "https://evanshortiss.com/rht-summit-2023-lab-guide/summit-2023-gitops-workshop-guide/main/m5-ci-cd/_images/ex8.gh-new-branch.png"
    ]
kind: ConfigMap
metadata:
  name: images-json
  labels:
    app: random-meme
